persei_x_project:
    resource: "@PerseiXProjectBundle/Resources/config/routing/routing.yml"
    type: rest
    defaults:
        _format: json

persei_x_user:
    resource: "@PerseiXUserBundle/Resources/routing/routing.yml"
