persei_x_user:
    resource: "@PerseiXUserBundle/Controller/"
    type:     annotation
    prefix:   /

persei_x_project:
    resource: "@PerseiXProjectBundle/Resources/config/routing/routing.yml"
    prefix:   "/api"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   "/api/doc"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"