security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SONATA_ADMIN: [ROLE_CUSTOM_USER]

    providers:
       perseix_user_provider:
          id: perseix_user_povider.user_provider

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api:
            pattern:    ^/api/me
            fos_oauth:  true
            stateless:  true
            provider:   perseix_user_provider

        api:
            pattern: ^/api/*
            anonymous: true

        sonata_admin:
            pattern: ^/
            form_login:
                provider: perseix_user_provider
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                 target: /admin
            anonymous:    true

    access_control:
        - { path: ^/api/me, roles: [ ROLE_CUSTOM_USER ] }
        - { path: ^/api/*, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/admin/*, roles: [ROLE_SONATA_ADMIN] }
