security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
       fos_userbundle:
          id: fos_user.user_provider.username

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        api_doc:
            pattern:    ^/api/doc
            anonymous: true

        registry:
            pattern:    ^/api/registry
            anonymous: true

        movies:
            pattern:    ^/api/movies
            anonymous: true

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            provider:   fos_userbundle

    access_control:
        - { path: ^/api/doc, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api/registry, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api/movies, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ ROLE_ADMIN ] }
