services:
#    _defaults:
#        autowire: false
#        autoconfigure: false
#        public: false
#
    jms_serializer.naming_strategy:
        class: 'JMS\Serializer\Naming\IdenticalPropertyNamingStrategy'