perseix_project_movies:
    path: /movies
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Movies:collection
        _format: json

perseix_project_single_movie:
    path: /movie/{movieId}
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Movies:single
        _format: json
    requirements:
        movieId: \d+

perseix_project_category_collection:
    path: /categories
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Category:collection
        _format: json