perseix_project_movies:
    path: /movies
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Movies:collection
        _format: json
        limit: 10
        page: 10
    requirements:
        limit: \d+
        page: \d+

perseix_project_single_movie:
    path: /movie/{movieId}
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Movies:single
        _format: json
    requirements:
        movieId: \d+


perseix_project_category_collection:
    path: /categories
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Category:collection
        _format: json
        limit: 10
        page: 10
    requirements:
        limit: \d+
        page: \d+


perseix_project_movies_collection_by_category_id:
    path: /category/{categoryId}/movies
    methods:
        - GET
    defaults:
        _controller: PerseiXProjectBundle:Movies:moviesByCategory
        _format: json
        limit: 10
        page: 10
    requirements:
        limit: \d+
        page: \d+
        categoryId: \d+