services:
    perseix_user_manager.reqistry_manager:
        class: PerseiX\UserBundle\Manager\RegistryManager
        arguments:
            - '@fos_user.user_manager.default'
            - '@perseix_user_service.registration'

    perseix_user_service.registration:
        class: PerseiX\UserBundle\Service\Registration
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.encoder_factory'