PerseiX\UserBundle\Model\RegistryModel:
    properties:
        email:
            - NotBlank: ~
            - NotNull: ~
            - Email: ~
            - PerseiX\UserBundle\Validator\Constraints\UniqueField:
                entityClass: PerseiX\UserBundle\Entity\UserModel
                field: email

        username:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 4
                max: 16
                minMessage: "Login jest zbyt krótki. Minimalna liczba znaków wynosi 4."
                maxMessage: "Login jest zbyt długi. Maksymalna liczba znaków wynosi 16."
            - PerseiX\UserBundle\Validator\Constraints\UniqueField:
                entityClass: PerseiX\UserBundle\Entity\UserModel
                field: username

        password:
            - NotBlank: ~
            - NotNull: ~
            - Length:
                min: 6
                max: 16
                minMessage: "Hasło jest zbyt krótki. Minimalna liczba znaków wynosi 6."
                maxMessage: "Hasło jest zbyt długi. Maksymalna liczba znaków wynosi 16."