services:
    repository.movie: &DEFULT_REPOSITORY
        class: Doctrine\ORM\EntityRepository
        factory:
            - '@doctrine.orm.entity_manager'
            - getRepository
        arguments:
            - 'PerseiXProjectBundle:Movie'
        tags:
            - { name: api.sort_and_filtered_repository }

    repository.category:
        <<: *DEFULT_REPOSITORY
        class: Doctrine\ORM\EntityRepository
        arguments:
            - 'PerseiXProjectBundle:Category'
