services:
    guzzle_client:
        class: GuzzleHttp\Client

    perseix_project_service.http_fetcher:
        class: PerseiX\ProjectBundle\Service\HttpFetcher
        arguments:
            - '@guzzle_client'

#    perseix_project_service.proxy_fetcher:
#        class: PerseiX\ProjectBundle\Service\ProxyFetcher
#        arguments:
#            - '@snc_redis.cache_client'
#            - '@perseix_project_service.http_fetcher'

    perseix_project_resolver.movie_collection_argument_resolver:
        class: PerseiX\ProjectBundle\Resolver\MovieCollectionArgumentResolver
        arguments:
#            - '@perseix_project_service.proxy_fetcher'
            - '@perseix_project_factory.movie_factory'
            - '@perseix_project_service.http_fetcher'
        tags:
            - { name: controller.argument_value_resolver }

    perseix_project_factory.movie_factory:
         class: PerseiX\ProjectBundle\Factory\MovieFactory

    perseix_project_listener_cors:
        class: PerseiX\ProjectBundle\Listener\Cors\CorsListener
        tags:
            - { name: "kernel.event_listener", event: "kernel.request", method: "onKernelRequest", priority: 300 }
            - { name: "kernel.event_listener", event: "kernel.response", method: "onKernelResponse"}
