services:
    perseix_transformer.movie_transformer:
        class: PerseiX\ProjectBundle\Transformer\MovieTransformer
        tags:
            - { name: api.transformer }
        calls:
            - ['setImagePathResolver', ['@perseix_admin_resolver.image_path_resolver']]

    preseix_transformer_collection.movie_collection_transformer:
        class: PerseiX\ProjectBundle\Transformer\Collection\MovieCollectionTransformer
        parent: 'abstract.transformer'
        tags:
            - { name: api.transformer }

    perseix_transformer.category_transformer:
        class: PerseiX\ProjectBundle\Transformer\CategoryTransformer
        tags:
            - { name: api.transformer }

    preseix_transformer_collection.category_collection_transformer:
        class: PerseiX\ProjectBundle\Transformer\Collection\CategoryCollectionTransformer
        parent: 'abstract.transformer'
        tags:
            - { name: api.transformer }

    preseix_transformer_scope_category.movie_scope:
        class: PerseiX\ProjectBundle\Transformer\Scope\Category\MovieScope
        parent: 'api.abstract_transformer_scope'
        tags:
            - { name: api.transformer_scope }
